version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n_onecompany
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # Додайте ці змінні для базової автентифікації (замініть на свої)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=myuser
      - N8N_BASIC_AUTH_PASSWORD=mysecretpassword
      # Рекомендовано для збереження даних
      - GENERIC_TIMEZONE=Europe/Kyiv
      - TZ=Europe/Kyiv
    volumes:
      - ./n8n_data:/home/node/.n8n

volumes:
  n8n_data:
